var GAME_LEVELS = [
  ["                                                      x!!!x                     ",
   "                                                      xx!xx                     ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                       o o                      ",
   "                                                                                ",
   "                                                   xxx     xxx                  ",
   "                                    o o     xxx      x     x                    ",
   "                                                     xx!!!xx                    ",
   "                                   xxxxx              x!v!x                     ",
   "                                                       x x                  xx  ",
   "  xx                                                                         x  ",
   "  x            +        o                                                    x  ",
   "  x                                      xxx$$                             o x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxxxxx   xxxxxxxxxxxxxxxxxxxx     xxxxxxx   xxx%%xxxx  ",
   "                              x   x                  x !!! x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              x!!!x                  x!!!!!x                    ",
   "                              xxxxx                  xxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                      ",
   "                                                                                      ",
   "                                                                                      ",
   " x                                                                                    ",
   " x o                                                                                  ",
   " x                                                                                    ",
   " x                                                                                    ",
   " x                                                  x!!!!!x        x!!!!!x            ",
   " x                                                   x!v!x          x!v!x             ",
   " x                                                                                    ",
   " x                                                                                  x ",
   " xxxx                        o                                                      x ",
   " x                           o                                                      x ",
   " x                                                                                  x ",
   " x         xx!!!!xx           xxxxxx                                                x ",
   " x       +  x!!!!x            x    x                                                x ",
   " x          x!!!!x!!!!!!!!!!!!x    x                                                x ",
   " x  @       x!!!!x!!!!!!!!!!!!x    x                  o                o            x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$$xxxxxxxxxxxxxxxxx$$xxxxxxxxxxxxxxx%%xxxxx ",
   "                                                                                      "],
  ["                                                                                      ",
   " x                                                                                  x ",
   " x                                                                                  x ",
   " x                                                                             o    x ",
   " x                             o                                                    x ",
   " x                           xxxxx                                                  x ",
   " x                           x   x                                                  x ",
   " x             o             x   x                                             o    x ",
   " x  @                        x   x                                                  x ",
   " xxxxxxxxxxxxxxxxxxxxxxxxxxxxx   xxxxxxxxxxx!!!xxxx$$xxx      xxxx$$xxxx!!!xxxxxxxxxx ",
   " x                                         x!!!x       x      x                       ",
   " x                                         x!!!x       x      x                       ",
   " x                                 o       xxvxx       x      x                       ",
   " x                                                     x      x                       ",
   " x                                                     x      x                       ",
   " x        o     $                                      x      x                       ",
   " x              $                                             x                       ",
   " x              $             xx!!!!!!!xx                     x                       ",
   " x              $            xx!!!!!!!!!xx   +               xx                       ",
   " xx%%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx$$xxxxxxxxx                        ",
   "                                                                                      "],
   [" x         x   x   x     x  x    ",
    "  x   x   x    x   x x   x  x    ",
    "   x x x x     x   x   x x       ",
    "    x   x      x   x    xx  x    "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
